### ISSUE TITLE
Request for clarification: '[]', '$' in data

### ISSUE THREAD

**Issue by townxelliot** [LlGC-NLW/shippingrecords#1]
Could you please explain the meaning of the [] and $ characters in the data (especially for locations)?

My assumption is the '[...]' means a place name is tentative, and '$' means a character is illegible. Is this the case?

**Comment by Surfrdan** [comment]
Hi @townxelliot you are on the right lines. Here's an example of the key from the original transcribed tabular data

data | description
------ | --------------
$$$$$$ | Illegible Word 
$ | Illegible letter e.g  Aberystw$th 
[] e.g. [Aberystwyth] | Guess
blk | Blank 
yyyy-mm-dd or yyyy-mm or yyyy |  Date

**Comment by townxelliot** [comment]
Thanks @Surfrdan
